[package]
name = "notes-gpui"
version = "0.1.0"
edition = "2024"

[dependencies]
notes-core = { path = "../notes-core" }
gpui = { version = "*" }
unicode-segmentation = "1.9.0"
dirs = "6.0.0"

[dev-dependencies]
tempfile = "3.23.0"
